version: '3'

services:
  edgex-device-ttyusb:
    image: registry.jiangxingai.com:5000/edgex/device-service/ttyusb:arm64v8-cpu-0.0.1
    container_name: edgex-device-ttyusb
    hostname: edgex-device-ttyusb
    restart: always
    command: --dp /dev/ttyUSB4 --baud 115200
    privileged: true
    volumes:
      - "/dev:/dev"

networks:
  default:
    external:
      name: edgex
